In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

In [2]:
matplotlib.use('tkagg')
%matplotlib auto
%matplotlib auto

Using matplotlib backend: tkagg
Using matplotlib backend: tkagg


In [ ]:
data_root = '/home/fourier/GRX_humanoid/grx_sdk/'
sim_data_path = data_root + 'sim data/dreamwaq_log_250714_170420_replay_cmd.csv'
real_data_path = data_root + 'real data/dreamwaq_log_250714_163758.csv'

sim_data = np.loadtxt(sim_data_path, delimiter=',')
real_data = np.loadtxt(real_data_path, delimiter=',')

print(sim_data.shape)
print(real_data.shape)

In [ ]:
# parse data
ac_dim = 21
sim_time = sim_data[:, 0]
sim_ang_vel = sim_data[:, 1:4]
sim_grav_proj = sim_data[:, 4:7]
sim_jpos = sim_data[:, 7:7+ac_dim]
sim_jvel = sim_data[:, 7+ac_dim:7+2*ac_dim]
sim_action = sim_data[:, 7+2*ac_dim:7+3*ac_dim]
sim_gait_sig = sim_data[:, 7+3*ac_dim:7+3*ac_dim+4]
sim_cmd = sim_data[:, 7+3*ac_dim+4:7+3*ac_dim+4+3]
sim_tor = sim_data[:, 7+3*ac_dim+4+3+ac_dim:7+3*ac_dim+4+3+2*ac_dim]

real_time = real_data[:, 0]
real_ang_vel = real_data[:, 1:4]
real_grav_proj = real_data[:, 4:7]
real_jpos = real_data[:, 7:7+ac_dim]
real_jvel = real_data[:, 7+ac_dim:7+2*ac_dim]
real_action = real_data[:, 7+2*ac_dim:7+3*ac_dim]
real_gait_sig = real_data[:, 7+3*ac_dim:7+3*ac_dim+4]
real_cmd = real_data[:, 7+3*ac_dim+4:7+3*ac_dim+4+3]
real_tor = real_data[:, 7+3*ac_dim+4+3+ac_dim:7+3*ac_dim+4+3+2*ac_dim]

In [ ]:
fig, axs = plt.subplots(3, 1, figsize=(20, 15), sharex=True)
labels = ['wx', 'wy', 'wz']
for i in range(3):
    ax = axs[i]
    ax.plot(sim_time, sim_ang_vel[:, i], label=f'sim_{labels[i]}')
    ax.plot(real_time, real_ang_vel[:, i], label=f'real_{labels[i]}', linestyle='--')
    ax.legend()
fig.suptitle('Angular Velocity')
plt.tight_layout()

In [ ]:
fig, axs = plt.subplots(3, 1, figsize=(20, 15), sharex=True)
for i in range(3):
    ax = axs[i]
    ax.plot(sim_time, sim_grav_proj[:, i], label=f'sim_proj{i}')
    ax.plot(real_time, real_grav_proj[:, i], label=f'real_proj{i}', linestyle='--')
    ax.legend()
fig.suptitle('Gravitational Projection')
plt.tight_layout()

In [ ]:
fig, axs = plt.subplots(4, 6, figsize=(20, 15), sharex=True)
for i in range(ac_dim):
    ax = axs[i // 6, i % 6]
    ax.plot(sim_time, sim_jpos[:, i], label=f'sim_jpos_{i}')
    ax.plot(sim_time, sim_action[:, i], label=f'sim_action_{i}', linestyle='--')
    # ax.plot(real_time, real_jpos[:, i], label=f'real_jpos_{i}')
    # ax.plot(real_time, real_action[:, i], label=f'real_action_{i}', linestyle='--')
    ax.legend()
fig.suptitle('sim jpos and action')
plt.tight_layout()

In [ ]:
fig, axs = plt.subplots(4, 6, figsize=(20, 15), sharex=True)
for i in range(ac_dim):
    ax = axs[i // 6, i % 6]
    # ax.plot(sim_time, sim_jpos[:, i], label=f'sim_jpos_{i}')
    # ax.plot(sim_time, sim_action[:, i], label=f'sim_action_{i}', linestyle='--')
    ax.plot(real_time, real_jpos[:, i], label=f'real_jpos_{i}')
    ax.plot(real_time, real_action[:, i], label=f'real_action_{i}', linestyle='--')
    ax.legend()
    # ax.set_xlim([0, 8])
fig.suptitle('real jpos and action')
plt.tight_layout()

In [ ]:
fig, axs = plt.subplots(4, 6, figsize=(20, 15), sharex=True)
for i in range(ac_dim):
    ax = axs[i // 6, i % 6]
    ax.plot(sim_time, sim_jvel[:, i], label=f'sim_jvel_{i}')
    ax.plot(real_time, real_jvel[:, i], label=f'real_jvel_{i}', linestyle='--')
    ax.legend()
fig.suptitle('jvel')
plt.tight_layout()

In [ ]:
fig, axs = plt.subplots(2, 2, figsize=(10, 15))
for i in range(4):
    ax = axs[i // 2, i % 2]
    ax.plot(sim_time, sim_gait_sig[:, i], label=f'sim_gait_sig_{i}')
    ax.plot(real_time, real_gait_sig[:, i], label=f'real_gait_sig_{i}', linestyle='--')
    ax.legend()

In [ ]:
fig, axs = plt.subplots(3, 1, figsize=(10, 15))
for i in range(3):
    ax = axs[i]
    ax.plot(sim_time, sim_cmd[:, i], label=f'sim_cmd_{i}')
    # ax.plot(real_time, real_cmd[:, i], label=f'real_cmd_{i}', linestyle='--')
    ax.legend()
fig.suptitle('Command Signals')
plt.tight_layout()

In [ ]:
fig, axs = plt.subplots(4, 6, figsize=(20, 15), sharex=True)
for i in range(ac_dim):
    ax = axs[i // 6, i % 6]
    ax.plot(sim_time, sim_tor[:, i], label=f'sim_tor_{i}')
    ax.plot(real_time, real_tor[:, i], label=f'real_tor_{i}', linestyle='--')
    ax.legend()
fig.suptitle('torques')
plt.tight_layout()

In [ ]:
sim_dt = sim_time[1:] - sim_time[0:-1]
real_dt = real_time[1:] - real_time[0:-1]
print(f"sim dt: {np.mean(sim_dt):.4f} +/- {np.std(sim_dt):.4f}")
print(f"real dt: {np.mean(real_dt):.4f} +/- {np.std(real_dt):.4f}")
plt.plot(sim_dt, label='sim_dt')
plt.plot(real_dt, label='real_dt')
plt.show()
plt.legend()

In [2]:
import torch
# a = torch.bernoulli(0.3*torch.ones((3, 10)))
time = torch.rand(8)
a = torch.rand(8, 6)
print(time)
print(a)
exec_ids = torch.where(time > 0.5)[0]
delay_ids = torch.where(a[:,0] > 0.5)[0]
print(exec_ids)
print(delay_ids)
print("Execution IDs:", a[exec_ids])
exec_delay = torch.where(a[exec_ids][:,0] > 0.5)[0]
print("exec_delay:", exec_delay)
print(exec_ids)
print(exec_ids[exec_delay])

tensor([0.1147, 0.0453, 0.5480, 0.3348, 0.4984, 0.9475, 0.7886, 0.0250])
tensor([[0.2021, 0.6796, 0.3544, 0.6807, 0.8856, 0.8644],
        [0.7525, 0.9003, 0.5109, 0.0921, 0.8146, 0.0745],
        [0.6713, 0.9656, 0.8994, 0.2801, 0.0816, 0.9590],
        [0.0342, 0.3047, 0.5885, 0.3560, 0.9598, 0.0185],
        [0.7343, 0.8505, 0.1165, 0.8890, 0.0358, 0.1223],
        [0.7335, 0.4277, 0.9746, 0.4568, 0.6634, 0.0024],
        [0.4059, 0.7699, 0.5125, 0.3221, 0.3640, 0.0577],
        [0.8215, 0.4178, 0.7027, 0.1480, 0.8844, 0.6098]])
tensor([2, 5, 6])
tensor([1, 2, 4, 5, 7])
Execution IDs: tensor([[0.6713, 0.9656, 0.8994, 0.2801, 0.0816, 0.9590],
        [0.7335, 0.4277, 0.9746, 0.4568, 0.6634, 0.0024],
        [0.4059, 0.7699, 0.5125, 0.3221, 0.3640, 0.0577]])
exec_delay: tensor([0, 1])
tensor([2, 5, 6])
tensor([2, 5])


In [117]:
data_root = '/home/fourier/GRX_humanoid/grxisaaclab/'
data_path = data_root + 'logs/rsl_rl/ppv210_humanoid_rough_wbc_full/2025-09-13_18-39-46'

data = np.load(data_path + '/cmd_track_data.npy')
joint_data = np.load(data_path + '/joint_states.npy')
action = np.load(data_path + '/actions.npy')

print(data.shape)
print(joint_data.shape)
print(action.shape)

(1000, 46)
(1000, 124)
(1000, 31)


In [33]:
# def matrix_from_quat(quaternions: torch.Tensor) -> torch.Tensor:
#     """Convert rotations given as quaternions to rotation matrices.

#     Args:
#         quaternions: The quaternion orientation in (w, x, y, z). Shape is (..., 4).

#     Returns:
#         Rotation matrices. The shape is (..., 3, 3).

#     Reference:
#         https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/transforms/rotation_conversions.py#L41-L70
#     """
#     r, i, j, k = torch.unbind(quaternions, -1)
#     # pyre-fixme[58]: `/` is not supported for operand types `float` and `Tensor`.
#     two_s = 2.0 / (quaternions * quaternions).sum(-1)

#     o = torch.stack(
#         (
#             1 - two_s * (j * j + k * k),
#             two_s * (i * j - k * r),
#             two_s * (i * k + j * r),
#             two_s * (i * j + k * r),
#             1 - two_s * (i * i + k * k),
#             two_s * (j * k - i * r),
#             two_s * (i * k - j * r),
#             two_s * (j * k + i * r),
#             1 - two_s * (i * i + j * j),
#         ),
#         -1,
#     )
#     return o.reshape(quaternions.shape[:-1] + (3, 3))

def matrix_from_quat_np(quaternions: np.ndarray) -> np.ndarray:
    """Convert rotations given as quaternions to rotation matrices.

    Args:
        quaternions: The quaternion orientation in (w, x, y, z). Shape is (..., 4).

    Returns:
        Rotation matrices. The shape is (..., 3, 3).
    """
    r, i, j, k = np.split(quaternions, 4, axis=-1)
    two_s = 2.0 / np.sum(quaternions * quaternions, axis=-1, keepdims=True)

    o = np.stack(
        (
            1 - two_s * (j * j + k * k),
            two_s * (i * j - k * r),
            two_s * (i * k + j * r),
            two_s * (i * j + k * r),
            1 - two_s * (i * i + k * k),
            two_s * (j * k - i * r),
            two_s * (i * k - j * r),
            two_s * (j * k + i * r),
            1 - two_s * (i * i + j * j),
        ),
        axis=-1,
    )
    return o.reshape(quaternions.shape[:-1] + (3, 3))

In [118]:
vel_cmd = data[:, :3]
base_lin_vel = data[:, 3:5]
base_ang_vel = data[:, 5:6]
height_torso_cmd = data[:, 6:10]
base_height = data[:, 10:11]
torso_zxy = data[:, 11:14]  # zxy euler angles
upper_joint_cmd = data[:, 14:30]
upper_joint_pos = data[:, 30:46]

jPos_targ = joint_data[:, 0:31]  # joint positions
jPos = joint_data[:, 31:62]  # joint positions
jVel = joint_data[:, 62:93]  # joint velocities
jTor = joint_data[:, 93:124]  # joint torques

# torso_orient = data[:, 11:15] #quat
# upper_joint_cmd = data[:, 15:31]
# upper_joint_pos = data[:, 31:47]

# torso_mat = matrix_from_quat_np(torso_orient)
# torso_yaw = np.arctan2(-torso_mat[:, 0, 1], torso_mat[:, 1, 1])
# torso_roll = np.arcsin(torso_mat[:, 2, 1])
# torso_pitch = np.arctan2(-torso_mat[:, 2, 0], torso_mat[:, 2, 2])

In [91]:
fig, axs = plt.subplots(2, 4, figsize=(40, 20), sharex=True)

axs[0, 0].plot(vel_cmd[:, 0], label='vel_cmd X')
axs[0, 0].plot(base_lin_vel[:, 0], label='base_lin_vel X')
axs[0, 0].set_title("lin vel X")

axs[0, 1].plot(vel_cmd[:, 1], label='vel_cmd Y')
axs[0, 1].plot(base_lin_vel[:, 1], label='base_lin_vel Y')
axs[0, 1].set_title("lin vel Y")

axs[0, 2].plot(vel_cmd[:, 2], label='vel_cmd Z')
axs[0, 2].plot(base_ang_vel[:, 0], label='base_ang_vel Z')
axs[0, 2].set_title("lin vel Z")

axs[0, 3].plot(height_torso_cmd[:,0], label='height cmd')
axs[0, 3].plot(base_height[:, 0], label='base height')
axs[0, 3].set_title("Height Command")

axs[1, 0].plot(height_torso_cmd[:, 1], label='torso cmd Z')
axs[1, 0].plot(torso_zxy[:,0], label='torso Z')
axs[1, 0].set_title("torso yaw")

axs[1, 1].plot(height_torso_cmd[:, 2], label='torso cmd X')
axs[1, 1].plot(torso_zxy[:,1], label='torso roll')
axs[1, 1].set_title("Torso Roll")

axs[1, 2].plot(height_torso_cmd[:, 3], label='torso cmd Y')
axs[1, 2].plot(torso_zxy[:,2], label='torso pitch')
axs[1, 2].set_title("Torso Pitch")

plt.tight_layout()
plt.legend()
plt.show()

/tmp/ipykernel_2026358/349232525.py:32: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()


/home/fourier/anaconda3/envs/env_isaaclab/lib/python3.10/tkinter/__init__.py:839: UserWarning: Glyph 27531 (\N{CJK UNIFIED IDEOGRAPH-6B8B}) missing from font(s) DejaVu Sans.
  func(*args)
/home/fourier/anaconda3/envs/env_isaaclab/lib/python3.10/tkinter/__init__.py:839: UserWarning: Glyph 24046 (\N{CJK UNIFIED IDEOGRAPH-5DEE}) missing from font(s) DejaVu Sans.
  func(*args)


In [113]:
ppv210_joint_names = ["left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint", \
                    "left_knee_pitch_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint", \
                    "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint",  \
                    "right_knee_pitch_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint",\
                    "waist_yaw_joint", "waist_roll_joint","waist_pitch_joint", \
                    "head_yaw_joint", "head_pitch_joint",\
                    "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_pitch_joint", \
                    "left_wrist_yaw_joint", "left_wrist_pitch_joint", "left_wrist_roll_joint", \
                    "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_pitch_joint", \
                    "right_wrist_yaw_joint", "right_wrist_pitch_joint", "right_wrist_roll_joint"]
upper_joint_names = [   "head_yaw_joint", "head_pitch_joint",\
                        "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_pitch_joint", \
                        "left_wrist_yaw_joint", "left_wrist_pitch_joint", "left_wrist_roll_joint", \
                        "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_pitch_joint", \
                        "right_wrist_yaw_joint", "right_wrist_pitch_joint", "right_wrist_roll_joint"]
lower_joint_names = [   "left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint", \
                        "left_knee_pitch_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint", \
                        "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint",  \
                        "right_knee_pitch_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint",\
                        "waist_yaw_joint", "waist_roll_joint","waist_pitch_joint"]
upper_joint_ids = [11, 16, 12, 17, 21, 23, 25, 27, 29, 13, 18, 22, 24, 26, 28, 30]
wb_joint_ids = [0, 3, 6, 9, 14, 19, 1, 4, 7, 10, 15, 20, 2, 5, 8, 11, 16, 12, 17, 21, 23, 25, 27, 29, 13, 18, 22, 24, 26, 28, 30]


fig, axs = plt.subplots(4, 4, figsize=(40, 20), sharex=True)
for i in range(16):
    ax = axs[i // 4, i % 4]
    ax.plot(upper_joint_cmd[:, i], label=f'upper_joint_cmd_{upper_joint_names[i]}')
    ax.plot(upper_joint_pos[:, i], label=f'upper_joint_pos_{upper_joint_names[i]}', linestyle='--')
    ax.plot(jPos_targ[:, i+15], label=f'jPos_Targ_{upper_joint_names[i]}', linestyle=':')
    ax.set_title(upper_joint_names[i])
    ax.legend()
plt.tight_layout()
# plt.suptitle("wbc_vert14")
# plt.suptitle("残差_0928")

# fig, axs = plt.subplots(4, 4, figsize=(40, 20), sharex=True)
# delta_pos = upper_joint_cmd - upper_joint_pos
# for i in range(16):
#     ax = axs[i // 4, i % 4]
#     ax.plot(delta_pos[:-1, i], label=f'delta_pos_{upper_joint_names[i]}')
#     ax.set_title(upper_joint_names[i])
#     ax.legend()
# plt.tight_layout()

# fig, axs = plt.subplots(4, 4, figsize=(40, 20), sharex=True)
# for i in range(14):
#     ax = axs[i // 4, i % 4]
#     ax.plot(jPos_targ[:, i], label=f'action_{upper_joint_names[i]}')
#     ax.plot(jPos[:, i], label=f'jPos_{upper_joint_names[i]}', linestyle='--')
#     ax.legend()
# plt.tight_layout()

In [53]:
fig, axs = plt.subplots(4, 4, figsize=(40, 20), sharex=True)
for i in range(16):
    ax = axs[i // 4, i % 4]
    ax.plot(jVel[:, i+15], label=f'jVel_{upper_joint_names[i]}')
    ax.legend()
plt.tight_layout()
plt.suptitle("wbc_vert14")
# plt.suptitle("残差_0928")


Text(0.5, 0.98, 'wbc_vert14')

/home/fourier/anaconda3/envs/env_isaaclab/lib/python3.10/tkinter/__init__.py:1921: UserWarning: Glyph 27531 (\N{CJK UNIFIED IDEOGRAPH-6B8B}) missing from font(s) DejaVu Sans.
  return self.func(*args)
/home/fourier/anaconda3/envs/env_isaaclab/lib/python3.10/tkinter/__init__.py:1921: UserWarning: Glyph 24046 (\N{CJK UNIFIED IDEOGRAPH-5DEE}) missing from font(s) DejaVu Sans.
  return self.func(*args)


In [119]:
fig, axs = plt.subplots(4, 4, figsize=(40, 20), sharex=True)
for i in range(15):
    ax = axs[i // 4, i % 4]
    # ax.plot(jTor[:, i+15], label=f'jTor_{upper_joint_names[i]}')
    ax.plot(jTor[:, i], label=f'jTor_{lower_joint_names[i]}')
    ax.legend()
    ax2 = ax.twinx()
    ax2.plot(base_height[:, 0], label='base height', color='orange', linestyle=':')
plt.tight_layout()
# plt.suptitle("wbc_vert14")
# plt.suptitle("残差_0928")


In [120]:
fig, axs = plt.subplots(4, 4, figsize=(40, 20), sharex=True)
for i in range(15):
    ax = axs[i // 4, i % 4]
    ax.plot(jPos_targ[:, i], label=f'jPos_Targ_{lower_joint_names[i]}')
    ax.plot(jPos[:,i], label=f'jPos_{lower_joint_names[i]}')
    ax.set_title(lower_joint_names[i])
    ax.legend()
    ax2 = ax.twinx()
    ax2.plot(base_height[:, 0], label='base height', color='orange', linestyle=':')
plt.tight_layout()

In [36]:
fig, axs = plt.subplots(4, 4, figsize=(40, 20), sharex=True)
for i in range(16):
    ax = axs[i // 4, i % 4]
    ax.plot(jTor[:, i+15], label=f'jTor_{upper_joint_names[i]}')
    ax.legend()
    ax2 = ax.twinx()
    ax2.plot(jPos_targ[:, i+15], label=f'action_{upper_joint_names[i]}', color='orange', linestyle='--')
    ax2.legend(loc='upper right')
plt.tight_layout()