In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import os

In [2]:
matplotlib.use('tkagg')
%matplotlib auto
%matplotlib auto

Using matplotlib backend: tkagg
Using matplotlib backend: tkagg


In [14]:
current_folder = os.getcwd()
print(f"Current folder: {current_folder}")

Current folder: /home/fourier/GRX_humanoid/grxisaaclab/test_script


In [15]:
# obs_data = np.load(current_folder + "/../scripts/obs_data.npy")
obs_data = np.load("/home/fourier/GRX_humanoid/grxisaaclab/logs/rsl_rl/ppv210_humanoid_rough_wbc_full/2025-07-27_19-29-36/obs_data.npy")
print(f"obs_data shape: {obs_data.shape}")

obs_data shape: (1000, 4960)


In [16]:
# history length = 40
base_ang_vel = obs_data[:, 0:120]
proj_gravity = obs_data[:, 120:240]
is_walk_flag = obs_data[:, 240:280]
vel_cmd = obs_data[:, 280:400]
hgt_cmd = obs_data[:, 400:480]
jpos_cmd = obs_data[:, 480:1240]
jpos = obs_data[:, 1240:2480]
jvel = obs_data[:, 2480:3720]
action = obs_data[:, 3720:4960]

In [ ]:
ppv210_upper_joint_names = ["waist_yaw_joint", "waist_roll_joint","waist_pitch_joint", \
                        "head_yaw_joint", "head_pitch_joint",\
                        "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_pitch_joint", \
                        "left_wrist_yaw_joint", "left_wrist_pitch_joint", "left_wrist_roll_joint", \
                        "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_pitch_joint", \
                        "right_wrist_yaw_joint", "right_wrist_pitch_joint", "right_wrist_roll_joint"]

In [18]:
jpos_cmd_single = jpos_cmd[:, :19]
fig, axs = plt.subplots(4, 5, figsize=(18, 9), sharex = True)
for i, joint_name in enumerate(ppv210_upper_joint_names):
    ax = axs[i // 5, i % 5]
    ax.plot(jpos_cmd_single[:, i], label=joint_name)
    ax.legend()

In [3]:
import torch

In [1]:
# Bernoulli 分布测试
prob = 0.5
prob_seq = torch.bernoulli(torch.tensor([prob] * 50))
print("Bernoulli distribution probabilities:", prob_seq)
plt.plot(prob_seq.numpy(), label='Bernoulli Probabilities')

NameError: name 'torch' is not defined

In [13]:
a= torch.rand(4,9)
print(a)
row_idx = torch.tensor([0,2])
col_idx = torch.tensor([1,3,4,5,7])
print(a[row_idx][:, col_idx])
a[row_idx.unsqueeze(1), col_idx] = 0
print(a)

tensor([[0.2671, 0.7455, 0.6288, 0.5129, 0.1645, 0.1502, 0.1815, 0.6741, 0.5280],
        [0.9829, 0.6512, 0.6472, 0.6564, 0.8941, 0.4557, 0.9898, 0.0285, 0.6484],
        [0.8362, 0.0800, 0.1702, 0.4608, 0.4924, 0.2193, 0.3745, 0.3194, 0.8227],
        [0.4644, 0.1104, 0.9217, 0.1140, 0.5861, 0.3426, 0.6406, 0.0743, 0.0483]])
tensor([[0.7455, 0.5129, 0.1645, 0.1502, 0.6741],
        [0.0800, 0.4608, 0.4924, 0.2193, 0.3194]])
tensor([[0.2671, 0.0000, 0.6288, 0.0000, 0.0000, 0.0000, 0.1815, 0.0000, 0.5280],
        [0.9829, 0.6512, 0.6472, 0.6564, 0.8941, 0.4557, 0.9898, 0.0285, 0.6484],
        [0.8362, 0.0000, 0.1702, 0.0000, 0.0000, 0.0000, 0.3745, 0.0000, 0.8227],
        [0.4644, 0.1104, 0.9217, 0.1140, 0.5861, 0.3426, 0.6406, 0.0743, 0.0483]])


In [3]:
ppv210_joint_names = ["left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint", \
                    "left_knee_pitch_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint", \
                    "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint",  \
                    "right_knee_pitch_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint",\
                    "waist_yaw_joint", "waist_roll_joint","waist_pitch_joint", \
                    "head_yaw_joint", "head_pitch_joint",\
                    "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_pitch_joint", \
                    "left_wrist_yaw_joint", "left_wrist_pitch_joint", "left_wrist_roll_joint", \
                    "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_pitch_joint", \
                    "right_wrist_yaw_joint", "right_wrist_pitch_joint", "right_wrist_roll_joint"]
ppv210_upper_joint_names = [
                        # "waist_yaw_joint", "waist_roll_joint","waist_pitch_joint", \
                        "head_yaw_joint", "head_pitch_joint",\
                        "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_pitch_joint", \
                        "left_wrist_yaw_joint", "left_wrist_pitch_joint", "left_wrist_roll_joint", \
                        "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_pitch_joint", \
                        "right_wrist_yaw_joint", "right_wrist_pitch_joint", "right_wrist_roll_joint"]

ppv210_lower_joint_names = [
                        "waist_yaw_joint", "waist_roll_joint","waist_pitch_joint", \
                        "left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint", \
                        "left_knee_pitch_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint", \
                        "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint",  \
                        "right_knee_pitch_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint"]

In [5]:
ids = [ppv210_joint_names.index(name) for name in ppv210_upper_joint_names]
print(ids)

[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
